# -*- coding: utf-8 -*-
"""UNICEF_Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpMpLStQKLhpQblaMd8Wtl_3I7i45QyX

**Step : 1  Upload All Four Source Files**
"""

from google.colab import files
uploaded = files.upload()

"""**Step 2: Load & Clean Population Projections (2022)**"""

# Load Projections sheet, skipping metadata rows
proj_df = pd.read_excel(
    "WPP2022_GEN_F01_DEMOGRAPHIC_INDICATORS_COMPACT_REV1.xlsx",
    sheet_name="Projections",
    skiprows=16
)

# Filter to 2022, Medium variant, country/area
proj_2022 = proj_df[
    (proj_df['Year'] == 2022) &
    (proj_df['Variant'] == 'Medium') &
    (proj_df['Type'] == 'Country/Area')
][[
    'Region, subregion, country or area *',
    'ISO3 Alpha-code',
    'Births (thousands)'
]].rename(columns={
    'Region, subregion, country or area *': 'Country',
    'ISO3 Alpha-code': 'ISO3',
    'Births (thousands)': 'Births_Thousands'
})

proj_2022['Births'] = proj_2022['Births_Thousands'] * 1000
proj_2022 = proj_2022.dropna(subset=['ISO3'])

display(proj_2022.head())

"""**Step 3: Load & Process U5MR Status**"""

status_df = pd.read_excel("On-track and off-track countries.xlsx")
status_df = status_df.rename(columns={
    'ISO3Code': 'ISO3',
    'OfficialName': 'Country_Name',
    'Status.U5MR': 'U5MR_Status'
})

status_df['Group'] = status_df['U5MR_Status'].str.lower()\
                  .map(lambda x: 'On-track' if x in ['on-track','achieved'] else 'Off-track')


merged_df = proj_2022.merge(status_df[['ISO3','Group']], on='ISO3', how='inner')
display(merged_df.head())

"""**Step 4: Load & Clean ANC4 and SBA**"""

def clean_indicator(path, value_name):
    df = pd.read_excel(path, sheet_name="Unicef data")
    df = df[
        (df["Sex"] == "Total") &
        (df["TIME_PERIOD"].between(2018, 2022)) &
        (~df["Geographic area"].str.startswith("("))
    ]
    latest = (df.sort_values("TIME_PERIOD")
               .drop_duplicates("Geographic area", keep="last")
               .loc[:, ["Geographic area", "OBS_VALUE"]]
               .rename(columns={
                   "Geographic area": "Country",
                   "OBS_VALUE": value_name
               }))
    return latest

anc4_latest = clean_indicator("ANC4_long.xlsx", "ANC4")
sba_latest  = clean_indicator("SBA_long.xlsx", "SBA")

display(anc4_latest.head(), sba_latest.head())

"""**Step 5: Merge All & Compute Weighted Coverage**"""

df = merged_df.merge(anc4_latest, on="Country", how="left")\
              .merge(sba_latest,  on="Country", how="left")

for service in ["ANC4","SBA"]:
    for grp in ["On-track","Off-track"]:
        sub = df[df["Group"] == grp]
        wavg = (sub[service] * sub["Births"]).sum() / sub["Births"].sum()
        print(f"{service} ({grp}): {wavg:.1f}%")

"""## **Step 6: Visualize the Results**"""

import numpy as np
import matplotlib.pyplot as plt

# Services and values
services = ["ANC4", "SBA"]
ontrack = [46.7, 60.3]
offtrack = [49.9, 67.5]

x = np.arange(len(services))
width = 0.35

fig, ax = plt.subplots()
ax.bar(x - width/2, ontrack, width, label="On-track")
ax.bar(x + width/2, offtrack, width, label="Off-track")

ax.set_xticks(x)
ax.set_xticklabels(services)
ax.set_ylabel("Coverage (%)")
ax.set_title("Population-weighted Coverage: On-track vs Off-track")
ax.legend()

plt.tight_layout()
plt.show()

"""## Additional Visualizations

**Distribution Boxplots by Group**

* This shows you the spread of country‑level ANC4 and SBA coverages for On‑track vs Off‑track.
"""

import matplotlib.pyplot as plt

anc4_on  = df.loc[df["Group"]=="On-track",  "ANC4"].dropna()
anc4_off = df.loc[df["Group"]=="Off-track", "ANC4"].dropna()

sba_on   = df.loc[df["Group"]=="On-track",  "SBA"].dropna()
sba_off  = df.loc[df["Group"]=="Off-track", "SBA"].dropna()

# ANC4
plt.figure()
plt.boxplot([anc4_on, anc4_off], labels=["On-track","Off-track"])
plt.title("ANC4 Coverage Distribution by U5MR Group")
plt.ylabel("ANC4 (%)")
plt.tight_layout()
plt.show()

# SBA
plt.figure()
plt.boxplot([sba_on, sba_off], labels=["On-track","Off-track"])
plt.title("SBA Coverage Distribution by U5MR Group")
plt.ylabel("SBA (%)")
plt.tight_layout()
plt.show()

"""**Scatter of Coverage vs. Births**


*   This helps you see whether country size (birth count) correlates with coverage, colored by group.


"""

# ANC4
plt.figure()
for grp, color in [("On-track","C0"), ("Off-track","C1")]:
    sub = df[df["Group"]==grp]
    plt.scatter(sub["Births"], sub["ANC4"], label=grp, alpha=0.6)
plt.xscale("log")
plt.xlabel("2022 Births (log scale)")
plt.ylabel("ANC4 (%)")
plt.title("ANC4 Coverage vs Births by U5MR Group")
plt.legend()
plt.tight_layout()
plt.show()

# SBA
plt.figure()
for grp, color in [("On-track","C0"), ("Off-track","C1")]:
    sub = df[df["Group"]==grp]
    plt.scatter(sub["Births"], sub["SBA"], label=grp, alpha=0.6)
plt.xscale("log")
plt.xlabel("2022 Births (log scale)")
plt.ylabel("SBA (%)")
plt.title("SBA Coverage vs Births by U5MR Group")
plt.legend()
plt.tight_layout()
plt.show()



"""# Interpretation

Population‑weighted ANC4 coverage is slightly higher in off‑track countries (49.9%) than in on‑track ones (46.7%), suggesting that even where under‑five mortality improvements lag, antenatal service uptake remains relatively strong—possibly due to targeted maternal health programs. Conversely, SBA coverage shows a larger gap (67.5% vs. 60.3%), indicating that skilled birth attendance is more consistently available in countries ahead on mortality targets.
**Caveats & Assumptions:**


* We used 2022 medium‑variant birth projections from the UN WPP “Projections” sheet.
*   ANC4/SBA values reflect the most recent data between 2018–2022, which may vary by country in terms of exact year.
*   Country names/ISO3 matching may omit a few small territories if identifiers didn’t align exactly.
"""

# 4) Convert to HTML & PDF
!jupyter nbconvert --to html UNICEF_Assessment.ipynb --output outputs/Report.html

